// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package content

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/content/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ContentDetail        = pb.ContentDetail
	ContentSummary       = pb.ContentSummary
	CreateContentRequest = pb.CreateContentRequest
	GetContentRequest    = pb.GetContentRequest
	ListContentsRequest  = pb.ListContentsRequest
	ListContentsResponse = pb.ListContentsResponse
	UpdateContentRequest = pb.UpdateContentRequest
	UpdateStatusRequest  = pb.UpdateStatusRequest

	Content interface {
		ListPublicArticles(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error)
		ListContents(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error)
		CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*ContentDetail, error)
		GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*ContentDetail, error)
		UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*ContentDetail, error)
		UpdateContentStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*ContentDetail, error)
	}

	defaultContent struct {
		cli zrpc.Client
	}
)

func NewContent(cli zrpc.Client) Content {
	return &defaultContent{
		cli: cli,
	}
}

func (m *defaultContent) ListPublicArticles(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListPublicArticles(ctx, in, opts...)
}

func (m *defaultContent) ListContents(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListContents(ctx, in, opts...)
}

func (m *defaultContent) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateContent(ctx, in, opts...)
}

func (m *defaultContent) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.GetContent(ctx, in, opts...)
}

func (m *defaultContent) UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateContent(ctx, in, opts...)
}

func (m *defaultContent) UpdateContentStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateContentStatus(ctx, in, opts...)
}
