// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package content

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/content/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApproveReviewRequest       = pb.ApproveReviewRequest
	Attachment                 = pb.Attachment
	Comment                    = pb.Comment
	ContentDetail              = pb.ContentDetail
	ContentSummary             = pb.ContentSummary
	CreateAttachmentRequest    = pb.CreateAttachmentRequest
	CreateCommentRequest       = pb.CreateCommentRequest
	CreateContentRequest       = pb.CreateContentRequest
	CreateRelationRequest      = pb.CreateRelationRequest
	CreateTagRequest           = pb.CreateTagRequest
	DeleteAttachmentRequest    = pb.DeleteAttachmentRequest
	DeleteRelationRequest      = pb.DeleteRelationRequest
	DeleteTagRequest           = pb.DeleteTagRequest
	Empty                      = pb.Empty
	ExperienceProfile          = pb.ExperienceProfile
	GetContentRequest          = pb.GetContentRequest
	GetRevisionRequest         = pb.GetRevisionRequest
	ListAttachmentsRequest     = pb.ListAttachmentsRequest
	ListAttachmentsResponse    = pb.ListAttachmentsResponse
	ListCommentsRequest        = pb.ListCommentsRequest
	ListCommentsResponse       = pb.ListCommentsResponse
	ListContentsRequest        = pb.ListContentsRequest
	ListContentsResponse       = pb.ListContentsResponse
	ListRelationsRequest       = pb.ListRelationsRequest
	ListRelationsResponse      = pb.ListRelationsResponse
	ListTagsResponse           = pb.ListTagsResponse
	PortfolioProfile           = pb.PortfolioProfile
	ProjectProfile             = pb.ProjectProfile
	RejectReviewRequest        = pb.RejectReviewRequest
	Relation                   = pb.Relation
	RestoreRevisionRequest     = pb.RestoreRevisionRequest
	ReviewListRequest          = pb.ReviewListRequest
	ReviewListResponse         = pb.ReviewListResponse
	ReviewTask                 = pb.ReviewTask
	RevisionDetail             = pb.RevisionDetail
	RevisionListRequest        = pb.RevisionListRequest
	RevisionListResponse       = pb.RevisionListResponse
	RevisionSummary            = pb.RevisionSummary
	SubmitReviewRequest        = pb.SubmitReviewRequest
	Tag                        = pb.Tag
	TimelineEventProfile       = pb.TimelineEventProfile
	UpdateCommentStatusRequest = pb.UpdateCommentStatusRequest
	UpdateContentRequest       = pb.UpdateContentRequest
	UpdateStatusRequest        = pb.UpdateStatusRequest

	Content interface {
		ListPublicArticles(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error)
		ListContents(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error)
		CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*ContentDetail, error)
		GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*ContentDetail, error)
		UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*ContentDetail, error)
		UpdateContentStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*ContentDetail, error)
		ListTags(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTagsResponse, error)
		CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*Tag, error)
		DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*Empty, error)
		ListRelations(ctx context.Context, in *ListRelationsRequest, opts ...grpc.CallOption) (*ListRelationsResponse, error)
		CreateRelation(ctx context.Context, in *CreateRelationRequest, opts ...grpc.CallOption) (*Relation, error)
		DeleteRelation(ctx context.Context, in *DeleteRelationRequest, opts ...grpc.CallOption) (*Empty, error)
		ListAttachments(ctx context.Context, in *ListAttachmentsRequest, opts ...grpc.CallOption) (*ListAttachmentsResponse, error)
		CreateAttachment(ctx context.Context, in *CreateAttachmentRequest, opts ...grpc.CallOption) (*Attachment, error)
		DeleteAttachment(ctx context.Context, in *DeleteAttachmentRequest, opts ...grpc.CallOption) (*Empty, error)
		ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
		UpdateCommentStatus(ctx context.Context, in *UpdateCommentStatusRequest, opts ...grpc.CallOption) (*Comment, error)
		ListRevisions(ctx context.Context, in *RevisionListRequest, opts ...grpc.CallOption) (*RevisionListResponse, error)
		GetRevision(ctx context.Context, in *GetRevisionRequest, opts ...grpc.CallOption) (*RevisionDetail, error)
		RestoreRevision(ctx context.Context, in *RestoreRevisionRequest, opts ...grpc.CallOption) (*ContentDetail, error)
		ListReviews(ctx context.Context, in *ReviewListRequest, opts ...grpc.CallOption) (*ReviewListResponse, error)
		SubmitReview(ctx context.Context, in *SubmitReviewRequest, opts ...grpc.CallOption) (*ReviewTask, error)
		ApproveReview(ctx context.Context, in *ApproveReviewRequest, opts ...grpc.CallOption) (*ReviewTask, error)
		RejectReview(ctx context.Context, in *RejectReviewRequest, opts ...grpc.CallOption) (*ReviewTask, error)
	}

	defaultContent struct {
		cli zrpc.Client
	}
)

func NewContent(cli zrpc.Client) Content {
	return &defaultContent{
		cli: cli,
	}
}

func (m *defaultContent) ListPublicArticles(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListPublicArticles(ctx, in, opts...)
}

func (m *defaultContent) ListContents(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListContents(ctx, in, opts...)
}

func (m *defaultContent) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateContent(ctx, in, opts...)
}

func (m *defaultContent) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.GetContent(ctx, in, opts...)
}

func (m *defaultContent) UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateContent(ctx, in, opts...)
}

func (m *defaultContent) UpdateContentStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateContentStatus(ctx, in, opts...)
}

func (m *defaultContent) ListTags(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListTags(ctx, in, opts...)
}

func (m *defaultContent) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateTag(ctx, in, opts...)
}

func (m *defaultContent) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.DeleteTag(ctx, in, opts...)
}

func (m *defaultContent) ListRelations(ctx context.Context, in *ListRelationsRequest, opts ...grpc.CallOption) (*ListRelationsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListRelations(ctx, in, opts...)
}

func (m *defaultContent) CreateRelation(ctx context.Context, in *CreateRelationRequest, opts ...grpc.CallOption) (*Relation, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateRelation(ctx, in, opts...)
}

func (m *defaultContent) DeleteRelation(ctx context.Context, in *DeleteRelationRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.DeleteRelation(ctx, in, opts...)
}

func (m *defaultContent) ListAttachments(ctx context.Context, in *ListAttachmentsRequest, opts ...grpc.CallOption) (*ListAttachmentsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListAttachments(ctx, in, opts...)
}

func (m *defaultContent) CreateAttachment(ctx context.Context, in *CreateAttachmentRequest, opts ...grpc.CallOption) (*Attachment, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateAttachment(ctx, in, opts...)
}

func (m *defaultContent) DeleteAttachment(ctx context.Context, in *DeleteAttachmentRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.DeleteAttachment(ctx, in, opts...)
}

func (m *defaultContent) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}

func (m *defaultContent) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultContent) UpdateCommentStatus(ctx context.Context, in *UpdateCommentStatusRequest, opts ...grpc.CallOption) (*Comment, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateCommentStatus(ctx, in, opts...)
}

func (m *defaultContent) ListRevisions(ctx context.Context, in *RevisionListRequest, opts ...grpc.CallOption) (*RevisionListResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListRevisions(ctx, in, opts...)
}

func (m *defaultContent) GetRevision(ctx context.Context, in *GetRevisionRequest, opts ...grpc.CallOption) (*RevisionDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.GetRevision(ctx, in, opts...)
}

func (m *defaultContent) RestoreRevision(ctx context.Context, in *RestoreRevisionRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.RestoreRevision(ctx, in, opts...)
}

func (m *defaultContent) ListReviews(ctx context.Context, in *ReviewListRequest, opts ...grpc.CallOption) (*ReviewListResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListReviews(ctx, in, opts...)
}

func (m *defaultContent) SubmitReview(ctx context.Context, in *SubmitReviewRequest, opts ...grpc.CallOption) (*ReviewTask, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.SubmitReview(ctx, in, opts...)
}

func (m *defaultContent) ApproveReview(ctx context.Context, in *ApproveReviewRequest, opts ...grpc.CallOption) (*ReviewTask, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ApproveReview(ctx, in, opts...)
}

func (m *defaultContent) RejectReview(ctx context.Context, in *RejectReviewRequest, opts ...grpc.CallOption) (*ReviewTask, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.RejectReview(ctx, in, opts...)
}
