// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: identity.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/identity/internal/logic"
	"github.com/HappyLadySauce/Beehive-Blog/services/identity/internal/svc"
	"github.com/HappyLadySauce/Beehive-Blog/services/identity/pb"
)

type IdentityServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIdentityServer
}

func NewIdentityServer(svcCtx *svc.ServiceContext) *IdentityServer {
	return &IdentityServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.TokenReply, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *IdentityServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.TokenReply, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *IdentityServer) Refresh(ctx context.Context, in *pb.RefreshRequest) (*pb.TokenReply, error) {
	l := logic.NewRefreshLogic(ctx, s.svcCtx)
	return l.Refresh(in)
}

func (s *IdentityServer) GetUser(ctx context.Context, in *pb.GetUserRequest) (*pb.UserProfile, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
