// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ContentCreateRequest struct {
	ContentType  string `json:"type"`
	Title        string `json:"title"`
	Slug         string `json:"slug"`
	Summary      string `json:"summary,optional"`
	BodyMarkdown string `json:"bodyMarkdown"`
	Visibility   string `json:"visibility,optional"`
	AiAccess     string `json:"aiAccess,optional"`
}

type ContentDetail struct {
	Id           int64  `json:"id"`
	ContentType  string `json:"type"`
	Title        string `json:"title"`
	Slug         string `json:"slug"`
	Summary      string `json:"summary"`
	BodyMarkdown string `json:"bodyMarkdown"`
	Status       string `json:"status"`
	Visibility   string `json:"visibility"`
	AiAccess     string `json:"aiAccess"`
}

type ContentListRequest struct {
	Page        int64  `form:"page,optional"`
	PageSize    int64  `form:"pageSize,optional"`
	ContentType string `form:"type,optional"`
	Keyword     string `form:"keyword,optional"`
	Status      string `form:"status,optional"`
}

type ContentListResponse struct {
	List []ContentSummary `json:"list"`
}

type ContentSummary struct {
	Id          int64  `json:"id"`
	ContentType string `json:"type"`
	Title       string `json:"title"`
	Slug        string `json:"slug"`
	Summary     string `json:"summary"`
	Status      string `json:"status"`
	Visibility  string `json:"visibility"`
	AiAccess    string `json:"aiAccess"`
	PublishedAt string `json:"publishedAt,optional"`
}

type ContentUpdateRequest struct {
	Id           int64  `path:"id"`
	Title        string `json:"title,optional"`
	Summary      string `json:"summary,optional"`
	BodyMarkdown string `json:"bodyMarkdown,optional"`
	Visibility   string `json:"visibility,optional"`
	AiAccess     string `json:"aiAccess,optional"`
}

type ContentPathRequest struct {
	Id int64 `path:"id"`
}

type HealthResponse struct {
	Status  string `json:"status"`
	Service string `json:"service"`
}

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Nickname string `json:"nickname,optional"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SearchRequest struct {
	Query       string `form:"query"`
	Page        int64  `form:"page,optional"`
	PageSize    int64  `form:"pageSize,optional"`
	ContentType string `form:"type,optional"`
}

type SearchResponse struct {
	List []SearchResultItem `json:"list"`
}

type SearchResultItem struct {
	ContentId   int64   `json:"contentId"`
	ContentType string  `json:"type"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Summary     string  `json:"summary"`
	Highlight   string  `json:"highlight"`
	Score       float64 `json:"score"`
}

type StatusUpdateRequest struct {
	Id     int64  `path:"id"`
	Status string `json:"status"`
}

type TokenData struct {
	AccessToken  string      `json:"accessToken"`
	RefreshToken string      `json:"refreshToken"`
	ExpiresIn    int64       `json:"expiresIn"`
	User         UserProfile `json:"user"`
}

type UserProfile struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Role     string `json:"role"`
}
