// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/indexer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncOutboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchSize     int64                  `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOutboxRequest) Reset() {
	*x = SyncOutboxRequest{}
	mi := &file_proto_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOutboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOutboxRequest) ProtoMessage() {}

func (x *SyncOutboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOutboxRequest.ProtoReflect.Descriptor instead.
func (*SyncOutboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *SyncOutboxRequest) GetBatchSize() int64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type SyncOutboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Picked        int64                  `protobuf:"varint,1,opt,name=picked,proto3" json:"picked,omitempty"`
	Succeeded     int64                  `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        int64                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOutboxResponse) Reset() {
	*x = SyncOutboxResponse{}
	mi := &file_proto_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOutboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOutboxResponse) ProtoMessage() {}

func (x *SyncOutboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOutboxResponse.ProtoReflect.Descriptor instead.
func (*SyncOutboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *SyncOutboxResponse) GetPicked() int64 {
	if x != nil {
		return x.Picked
	}
	return 0
}

func (x *SyncOutboxResponse) GetSucceeded() int64 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *SyncOutboxResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_indexer_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_indexer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indexer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_indexer_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_indexer_proto protoreflect.FileDescriptor

const file_proto_indexer_proto_rawDesc = "" +
	"\n" +
	"\x13proto/indexer.proto\x12\aindexer\"2\n" +
	"\x11SyncOutboxRequest\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x03R\tbatchSize\"b\n" +
	"\x12SyncOutboxResponse\x12\x16\n" +
	"\x06picked\x18\x01 \x01(\x03R\x06picked\x12\x1c\n" +
	"\tsucceeded\x18\x02 \x01(\x03R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x03R\x06failed\"\a\n" +
	"\x05Empty\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x83\x01\n" +
	"\aIndexer\x12E\n" +
	"\n" +
	"SyncOutbox\x12\x1a.indexer.SyncOutboxRequest\x1a\x1b.indexer.SyncOutboxResponse\x121\n" +
	"\x06Health\x12\x0e.indexer.Empty\x1a\x17.indexer.HealthResponseB\x15Z\x13services/indexer/pbb\x06proto3"

var (
	file_proto_indexer_proto_rawDescOnce sync.Once
	file_proto_indexer_proto_rawDescData []byte
)

func file_proto_indexer_proto_rawDescGZIP() []byte {
	file_proto_indexer_proto_rawDescOnce.Do(func() {
		file_proto_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_indexer_proto_rawDesc), len(file_proto_indexer_proto_rawDesc)))
	})
	return file_proto_indexer_proto_rawDescData
}

var file_proto_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_indexer_proto_goTypes = []any{
	(*SyncOutboxRequest)(nil),  // 0: indexer.SyncOutboxRequest
	(*SyncOutboxResponse)(nil), // 1: indexer.SyncOutboxResponse
	(*Empty)(nil),              // 2: indexer.Empty
	(*HealthResponse)(nil),     // 3: indexer.HealthResponse
}
var file_proto_indexer_proto_depIdxs = []int32{
	0, // 0: indexer.Indexer.SyncOutbox:input_type -> indexer.SyncOutboxRequest
	2, // 1: indexer.Indexer.Health:input_type -> indexer.Empty
	1, // 2: indexer.Indexer.SyncOutbox:output_type -> indexer.SyncOutboxResponse
	3, // 3: indexer.Indexer.Health:output_type -> indexer.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_indexer_proto_init() }
func file_proto_indexer_proto_init() {
	if File_proto_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_indexer_proto_rawDesc), len(file_proto_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_indexer_proto_goTypes,
		DependencyIndexes: file_proto_indexer_proto_depIdxs,
		MessageInfos:      file_proto_indexer_proto_msgTypes,
	}.Build()
	File_proto_indexer_proto = out.File
	file_proto_indexer_proto_goTypes = nil
	file_proto_indexer_proto_depIdxs = nil
}
