// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Visibility    string                 `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	AiAccess      string                 `protobuf:"bytes,8,opt,name=ai_access,json=aiAccess,proto3" json:"ai_access,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentSummary) Reset() {
	*x = ContentSummary{}
	mi := &file_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSummary) ProtoMessage() {}

func (x *ContentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSummary.ProtoReflect.Descriptor instead.
func (*ContentSummary) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentSummary) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ContentSummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ContentSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentSummary) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ContentSummary) GetAiAccess() string {
	if x != nil {
		return x.AiAccess
	}
	return ""
}

func (x *ContentSummary) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type ContentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	BodyMarkdown  string                 `protobuf:"bytes,6,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Visibility    string                 `protobuf:"bytes,8,opt,name=visibility,proto3" json:"visibility,omitempty"`
	AiAccess      string                 `protobuf:"bytes,9,opt,name=ai_access,json=aiAccess,proto3" json:"ai_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentDetail) Reset() {
	*x = ContentDetail{}
	mi := &file_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentDetail) ProtoMessage() {}

func (x *ContentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentDetail.ProtoReflect.Descriptor instead.
func (*ContentDetail) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *ContentDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentDetail) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ContentDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ContentDetail) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

func (x *ContentDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentDetail) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ContentDetail) GetAiAccess() string {
	if x != nil {
		return x.AiAccess
	}
	return ""
}

type ListContentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentsRequest) Reset() {
	*x = ListContentsRequest{}
	mi := &file_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentsRequest) ProtoMessage() {}

func (x *ListContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentsRequest.ProtoReflect.Descriptor instead.
func (*ListContentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *ListContentsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContentsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListContentsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListContentsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListContentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ContentSummary      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentsResponse) Reset() {
	*x = ListContentsResponse{}
	mi := &file_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentsResponse) ProtoMessage() {}

func (x *ListContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentsResponse.ProtoReflect.Descriptor instead.
func (*ListContentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *ListContentsResponse) GetList() []*ContentSummary {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	BodyMarkdown  string                 `protobuf:"bytes,5,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	AiAccess      string                 `protobuf:"bytes,7,opt,name=ai_access,json=aiAccess,proto3" json:"ai_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_proto_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateContentRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateContentRequest) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

func (x *CreateContentRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreateContentRequest) GetAiAccess() string {
	if x != nil {
		return x.AiAccess
	}
	return ""
}

type UpdateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	BodyMarkdown  string                 `protobuf:"bytes,4,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	AiAccess      string                 `protobuf:"bytes,6,opt,name=ai_access,json=aiAccess,proto3" json:"ai_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentRequest) Reset() {
	*x = UpdateContentRequest{}
	mi := &file_proto_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentRequest) ProtoMessage() {}

func (x *UpdateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentRequest.ProtoReflect.Descriptor instead.
func (*UpdateContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateContentRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateContentRequest) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

func (x *UpdateContentRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *UpdateContentRequest) GetAiAccess() string {
	if x != nil {
		return x.AiAccess
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_proto_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{7}
}

func (x *GetContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_content_proto protoreflect.FileDescriptor

const file_proto_content_proto_rawDesc = "" +
	"\n" +
	"\x13proto/content.proto\x12\acontent\"\xf0\x01\n" +
	"\x0eContentSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tai_access\x18\b \x01(\tR\baiAccess\x12!\n" +
	"\fpublished_at\x18\t \x01(\tR\vpublishedAt\"\xf1\x01\n" +
	"\rContentDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12#\n" +
	"\rbody_markdown\x18\x06 \x01(\tR\fbodyMarkdown\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tai_access\x18\t \x01(\tR\baiAccess\"\x8c\x01\n" +
	"\x13ListContentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"C\n" +
	"\x14ListContentsResponse\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.content.ContentSummaryR\x04list\"\xd0\x01\n" +
	"\x14CreateContentRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12#\n" +
	"\rbody_markdown\x18\x05 \x01(\tR\fbodyMarkdown\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tai_access\x18\a \x01(\tR\baiAccess\"\xb8\x01\n" +
	"\x14UpdateContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12#\n" +
	"\rbody_markdown\x18\x04 \x01(\tR\fbodyMarkdown\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tai_access\x18\x06 \x01(\tR\baiAccess\"=\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"#\n" +
	"\x11GetContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xc8\x03\n" +
	"\aContent\x12Q\n" +
	"\x12ListPublicArticles\x12\x1c.content.ListContentsRequest\x1a\x1d.content.ListContentsResponse\x12K\n" +
	"\fListContents\x12\x1c.content.ListContentsRequest\x1a\x1d.content.ListContentsResponse\x12F\n" +
	"\rCreateContent\x12\x1d.content.CreateContentRequest\x1a\x16.content.ContentDetail\x12@\n" +
	"\n" +
	"GetContent\x12\x1a.content.GetContentRequest\x1a\x16.content.ContentDetail\x12F\n" +
	"\rUpdateContent\x12\x1d.content.UpdateContentRequest\x1a\x16.content.ContentDetail\x12K\n" +
	"\x13UpdateContentStatus\x12\x1c.content.UpdateStatusRequest\x1a\x16.content.ContentDetailB\x15Z\x13services/content/pbb\x06proto3"

var (
	file_proto_content_proto_rawDescOnce sync.Once
	file_proto_content_proto_rawDescData []byte
)

func file_proto_content_proto_rawDescGZIP() []byte {
	file_proto_content_proto_rawDescOnce.Do(func() {
		file_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)))
	})
	return file_proto_content_proto_rawDescData
}

var file_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_content_proto_goTypes = []any{
	(*ContentSummary)(nil),       // 0: content.ContentSummary
	(*ContentDetail)(nil),        // 1: content.ContentDetail
	(*ListContentsRequest)(nil),  // 2: content.ListContentsRequest
	(*ListContentsResponse)(nil), // 3: content.ListContentsResponse
	(*CreateContentRequest)(nil), // 4: content.CreateContentRequest
	(*UpdateContentRequest)(nil), // 5: content.UpdateContentRequest
	(*UpdateStatusRequest)(nil),  // 6: content.UpdateStatusRequest
	(*GetContentRequest)(nil),    // 7: content.GetContentRequest
}
var file_proto_content_proto_depIdxs = []int32{
	0, // 0: content.ListContentsResponse.list:type_name -> content.ContentSummary
	2, // 1: content.Content.ListPublicArticles:input_type -> content.ListContentsRequest
	2, // 2: content.Content.ListContents:input_type -> content.ListContentsRequest
	4, // 3: content.Content.CreateContent:input_type -> content.CreateContentRequest
	7, // 4: content.Content.GetContent:input_type -> content.GetContentRequest
	5, // 5: content.Content.UpdateContent:input_type -> content.UpdateContentRequest
	6, // 6: content.Content.UpdateContentStatus:input_type -> content.UpdateStatusRequest
	3, // 7: content.Content.ListPublicArticles:output_type -> content.ListContentsResponse
	3, // 8: content.Content.ListContents:output_type -> content.ListContentsResponse
	1, // 9: content.Content.CreateContent:output_type -> content.ContentDetail
	1, // 10: content.Content.GetContent:output_type -> content.ContentDetail
	1, // 11: content.Content.UpdateContent:output_type -> content.ContentDetail
	1, // 12: content.Content.UpdateContentStatus:output_type -> content.ContentDetail
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_content_proto_init() }
func file_proto_content_proto_init() {
	if File_proto_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_content_proto_goTypes,
		DependencyIndexes: file_proto_content_proto_depIdxs,
		MessageInfos:      file_proto_content_proto_msgTypes,
	}.Build()
	File_proto_content_proto = out.File
	file_proto_content_proto_goTypes = nil
	file_proto_content_proto_depIdxs = nil
}
