// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Visibility    string                 `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	AiAccess      string                 `protobuf:"bytes,8,opt,name=ai_access,json=aiAccess,proto3" json:"ai_access,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentSummary) Reset() {
	*x = ContentSummary{}
	mi := &file_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSummary) ProtoMessage() {}

func (x *ContentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSummary.ProtoReflect.Descriptor instead.
func (*ContentSummary) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentSummary) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ContentSummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ContentSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentSummary) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ContentSummary) GetAiAccess() string {
	if x != nil {
		return x.AiAccess
	}
	return ""
}

func (x *ContentSummary) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type ContentDetail struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary              string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	BodyMarkdown         string                 `protobuf:"bytes,6,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	Status               string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Visibility           string                 `protobuf:"bytes,8,opt,name=visibility,proto3" json:"visibility,omitempty"`
	AiAccess             string                 `protobuf:"bytes,9,opt,name=ai_access,json=aiAccess,proto3" json:"ai_access,omitempty"`
	ProjectProfile       *ProjectProfile        `protobuf:"bytes,10,opt,name=project_profile,json=projectProfile,proto3" json:"project_profile,omitempty"`
	ExperienceProfile    *ExperienceProfile     `protobuf:"bytes,11,opt,name=experience_profile,json=experienceProfile,proto3" json:"experience_profile,omitempty"`
	TimelineEventProfile *TimelineEventProfile  `protobuf:"bytes,12,opt,name=timeline_event_profile,json=timelineEventProfile,proto3" json:"timeline_event_profile,omitempty"`
	PortfolioProfile     *PortfolioProfile      `protobuf:"bytes,13,opt,name=portfolio_profile,json=portfolioProfile,proto3" json:"portfolio_profile,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ContentDetail) Reset() {
	*x = ContentDetail{}
	mi := &file_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentDetail) ProtoMessage() {}

func (x *ContentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentDetail.ProtoReflect.Descriptor instead.
func (*ContentDetail) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *ContentDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentDetail) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ContentDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ContentDetail) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

func (x *ContentDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentDetail) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ContentDetail) GetAiAccess() string {
	if x != nil {
		return x.AiAccess
	}
	return ""
}

func (x *ContentDetail) GetProjectProfile() *ProjectProfile {
	if x != nil {
		return x.ProjectProfile
	}
	return nil
}

func (x *ContentDetail) GetExperienceProfile() *ExperienceProfile {
	if x != nil {
		return x.ExperienceProfile
	}
	return nil
}

func (x *ContentDetail) GetTimelineEventProfile() *TimelineEventProfile {
	if x != nil {
		return x.TimelineEventProfile
	}
	return nil
}

func (x *ContentDetail) GetPortfolioProfile() *PortfolioProfile {
	if x != nil {
		return x.PortfolioProfile
	}
	return nil
}

type ListContentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentsRequest) Reset() {
	*x = ListContentsRequest{}
	mi := &file_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentsRequest) ProtoMessage() {}

func (x *ListContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentsRequest.ProtoReflect.Descriptor instead.
func (*ListContentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *ListContentsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContentsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListContentsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListContentsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListContentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ContentSummary      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentsResponse) Reset() {
	*x = ListContentsResponse{}
	mi := &file_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentsResponse) ProtoMessage() {}

func (x *ListContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentsResponse.ProtoReflect.Descriptor instead.
func (*ListContentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *ListContentsResponse) GetList() []*ContentSummary {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateContentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary              string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	BodyMarkdown         string                 `protobuf:"bytes,5,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	Visibility           string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	AiAccess             string                 `protobuf:"bytes,7,opt,name=ai_access,json=aiAccess,proto3" json:"ai_access,omitempty"`
	ProjectProfile       *ProjectProfile        `protobuf:"bytes,8,opt,name=project_profile,json=projectProfile,proto3" json:"project_profile,omitempty"`
	ExperienceProfile    *ExperienceProfile     `protobuf:"bytes,9,opt,name=experience_profile,json=experienceProfile,proto3" json:"experience_profile,omitempty"`
	TimelineEventProfile *TimelineEventProfile  `protobuf:"bytes,10,opt,name=timeline_event_profile,json=timelineEventProfile,proto3" json:"timeline_event_profile,omitempty"`
	PortfolioProfile     *PortfolioProfile      `protobuf:"bytes,11,opt,name=portfolio_profile,json=portfolioProfile,proto3" json:"portfolio_profile,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_proto_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateContentRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateContentRequest) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

func (x *CreateContentRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreateContentRequest) GetAiAccess() string {
	if x != nil {
		return x.AiAccess
	}
	return ""
}

func (x *CreateContentRequest) GetProjectProfile() *ProjectProfile {
	if x != nil {
		return x.ProjectProfile
	}
	return nil
}

func (x *CreateContentRequest) GetExperienceProfile() *ExperienceProfile {
	if x != nil {
		return x.ExperienceProfile
	}
	return nil
}

func (x *CreateContentRequest) GetTimelineEventProfile() *TimelineEventProfile {
	if x != nil {
		return x.TimelineEventProfile
	}
	return nil
}

func (x *CreateContentRequest) GetPortfolioProfile() *PortfolioProfile {
	if x != nil {
		return x.PortfolioProfile
	}
	return nil
}

type UpdateContentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary              string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	BodyMarkdown         string                 `protobuf:"bytes,4,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	Visibility           string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	AiAccess             string                 `protobuf:"bytes,6,opt,name=ai_access,json=aiAccess,proto3" json:"ai_access,omitempty"`
	ProjectProfile       *ProjectProfile        `protobuf:"bytes,7,opt,name=project_profile,json=projectProfile,proto3" json:"project_profile,omitempty"`
	ExperienceProfile    *ExperienceProfile     `protobuf:"bytes,8,opt,name=experience_profile,json=experienceProfile,proto3" json:"experience_profile,omitempty"`
	TimelineEventProfile *TimelineEventProfile  `protobuf:"bytes,9,opt,name=timeline_event_profile,json=timelineEventProfile,proto3" json:"timeline_event_profile,omitempty"`
	PortfolioProfile     *PortfolioProfile      `protobuf:"bytes,10,opt,name=portfolio_profile,json=portfolioProfile,proto3" json:"portfolio_profile,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateContentRequest) Reset() {
	*x = UpdateContentRequest{}
	mi := &file_proto_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentRequest) ProtoMessage() {}

func (x *UpdateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentRequest.ProtoReflect.Descriptor instead.
func (*UpdateContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateContentRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateContentRequest) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

func (x *UpdateContentRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *UpdateContentRequest) GetAiAccess() string {
	if x != nil {
		return x.AiAccess
	}
	return ""
}

func (x *UpdateContentRequest) GetProjectProfile() *ProjectProfile {
	if x != nil {
		return x.ProjectProfile
	}
	return nil
}

func (x *UpdateContentRequest) GetExperienceProfile() *ExperienceProfile {
	if x != nil {
		return x.ExperienceProfile
	}
	return nil
}

func (x *UpdateContentRequest) GetTimelineEventProfile() *TimelineEventProfile {
	if x != nil {
		return x.TimelineEventProfile
	}
	return nil
}

func (x *UpdateContentRequest) GetPortfolioProfile() *PortfolioProfile {
	if x != nil {
		return x.PortfolioProfile
	}
	return nil
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_proto_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{7}
}

func (x *GetContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{8}
}

type ProjectProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Stack         string                 `protobuf:"bytes,2,opt,name=stack,proto3" json:"stack,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	DemoUrl       string                 `protobuf:"bytes,4,opt,name=demo_url,json=demoUrl,proto3" json:"demo_url,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectProfile) Reset() {
	*x = ProjectProfile{}
	mi := &file_proto_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectProfile) ProtoMessage() {}

func (x *ProjectProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectProfile.ProtoReflect.Descriptor instead.
func (*ProjectProfile) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectProfile) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectProfile) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

func (x *ProjectProfile) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *ProjectProfile) GetDemoUrl() string {
	if x != nil {
		return x.DemoUrl
	}
	return ""
}

func (x *ProjectProfile) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ProjectProfile) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

type ExperienceProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgName       string                 `protobuf:"bytes,1,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperienceProfile) Reset() {
	*x = ExperienceProfile{}
	mi := &file_proto_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperienceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperienceProfile) ProtoMessage() {}

func (x *ExperienceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperienceProfile.ProtoReflect.Descriptor instead.
func (*ExperienceProfile) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{10}
}

func (x *ExperienceProfile) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *ExperienceProfile) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ExperienceProfile) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ExperienceProfile) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ExperienceProfile) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

type TimelineEventProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTime     string                 `protobuf:"bytes,1,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	EventCategory string                 `protobuf:"bytes,2,opt,name=event_category,json=eventCategory,proto3" json:"event_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEventProfile) Reset() {
	*x = TimelineEventProfile{}
	mi := &file_proto_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEventProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEventProfile) ProtoMessage() {}

func (x *TimelineEventProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEventProfile.ProtoReflect.Descriptor instead.
func (*TimelineEventProfile) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{11}
}

func (x *TimelineEventProfile) GetEventTime() string {
	if x != nil {
		return x.EventTime
	}
	return ""
}

func (x *TimelineEventProfile) GetEventCategory() string {
	if x != nil {
		return x.EventCategory
	}
	return ""
}

type PortfolioProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactType  string                 `protobuf:"bytes,1,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	ExternalLink  string                 `protobuf:"bytes,2,opt,name=external_link,json=externalLink,proto3" json:"external_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioProfile) Reset() {
	*x = PortfolioProfile{}
	mi := &file_proto_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioProfile) ProtoMessage() {}

func (x *PortfolioProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioProfile.ProtoReflect.Descriptor instead.
func (*PortfolioProfile) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{12}
}

func (x *PortfolioProfile) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *PortfolioProfile) GetExternalLink() string {
	if x != nil {
		return x.ExternalLink
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{13}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Tag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Tag                 `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_proto_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{14}
}

func (x *ListTagsResponse) GetList() []*Tag {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_proto_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{15}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTagRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateTagRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_proto_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteTagRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Relation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceContentId int64                  `protobuf:"varint,2,opt,name=source_content_id,json=sourceContentId,proto3" json:"source_content_id,omitempty"`
	TargetContentId int64                  `protobuf:"varint,3,opt,name=target_content_id,json=targetContentId,proto3" json:"target_content_id,omitempty"`
	RelationType    string                 `protobuf:"bytes,4,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Weight          int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Note            string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_proto_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{17}
}

func (x *Relation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Relation) GetSourceContentId() int64 {
	if x != nil {
		return x.SourceContentId
	}
	return 0
}

func (x *Relation) GetTargetContentId() int64 {
	if x != nil {
		return x.TargetContentId
	}
	return 0
}

func (x *Relation) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *Relation) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Relation) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ListRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelationsRequest) Reset() {
	*x = ListRelationsRequest{}
	mi := &file_proto_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationsRequest) ProtoMessage() {}

func (x *ListRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationsRequest.ProtoReflect.Descriptor instead.
func (*ListRelationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{18}
}

func (x *ListRelationsRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type ListRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Relation            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelationsResponse) Reset() {
	*x = ListRelationsResponse{}
	mi := &file_proto_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationsResponse) ProtoMessage() {}

func (x *ListRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationsResponse.ProtoReflect.Descriptor instead.
func (*ListRelationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{19}
}

func (x *ListRelationsResponse) GetList() []*Relation {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateRelationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceContentId int64                  `protobuf:"varint,1,opt,name=source_content_id,json=sourceContentId,proto3" json:"source_content_id,omitempty"`
	TargetContentId int64                  `protobuf:"varint,2,opt,name=target_content_id,json=targetContentId,proto3" json:"target_content_id,omitempty"`
	RelationType    string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Weight          int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Note            string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRelationRequest) Reset() {
	*x = CreateRelationRequest{}
	mi := &file_proto_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelationRequest) ProtoMessage() {}

func (x *CreateRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelationRequest.ProtoReflect.Descriptor instead.
func (*CreateRelationRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{20}
}

func (x *CreateRelationRequest) GetSourceContentId() int64 {
	if x != nil {
		return x.SourceContentId
	}
	return 0
}

func (x *CreateRelationRequest) GetTargetContentId() int64 {
	if x != nil {
		return x.TargetContentId
	}
	return 0
}

func (x *CreateRelationRequest) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *CreateRelationRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateRelationRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DeleteRelationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationRequest) Reset() {
	*x = DeleteRelationRequest{}
	mi := &file_proto_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationRequest) ProtoMessage() {}

func (x *DeleteRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRelationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Attachment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentId       int64                  `protobuf:"varint,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	StorageProvider string                 `protobuf:"bytes,3,opt,name=storage_provider,json=storageProvider,proto3" json:"storage_provider,omitempty"`
	Bucket          string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey       string                 `protobuf:"bytes,5,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	FileName        string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType        string                 `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Ext             string                 `protobuf:"bytes,8,opt,name=ext,proto3" json:"ext,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,9,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	UsageType       string                 `protobuf:"bytes,10,opt,name=usage_type,json=usageType,proto3" json:"usage_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_proto_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{22}
}

func (x *Attachment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Attachment) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *Attachment) GetStorageProvider() string {
	if x != nil {
		return x.StorageProvider
	}
	return ""
}

func (x *Attachment) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Attachment) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Attachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *Attachment) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Attachment) GetUsageType() string {
	if x != nil {
		return x.UsageType
	}
	return ""
}

type ListAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsRequest) Reset() {
	*x = ListAttachmentsRequest{}
	mi := &file_proto_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsRequest) ProtoMessage() {}

func (x *ListAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{23}
}

func (x *ListAttachmentsRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *ListAttachmentsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAttachmentsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAttachmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Attachment          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsResponse) Reset() {
	*x = ListAttachmentsResponse{}
	mi := &file_proto_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsResponse) ProtoMessage() {}

func (x *ListAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{24}
}

func (x *ListAttachmentsResponse) GetList() []*Attachment {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateAttachmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentId       int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	StorageProvider string                 `protobuf:"bytes,2,opt,name=storage_provider,json=storageProvider,proto3" json:"storage_provider,omitempty"`
	Bucket          string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey       string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	FileName        string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType        string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Ext             string                 `protobuf:"bytes,7,opt,name=ext,proto3" json:"ext,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,8,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	UsageType       string                 `protobuf:"bytes,9,opt,name=usage_type,json=usageType,proto3" json:"usage_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAttachmentRequest) Reset() {
	*x = CreateAttachmentRequest{}
	mi := &file_proto_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachmentRequest) ProtoMessage() {}

func (x *CreateAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{25}
}

func (x *CreateAttachmentRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *CreateAttachmentRequest) GetStorageProvider() string {
	if x != nil {
		return x.StorageProvider
	}
	return ""
}

func (x *CreateAttachmentRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CreateAttachmentRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *CreateAttachmentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateAttachmentRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *CreateAttachmentRequest) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *CreateAttachmentRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateAttachmentRequest) GetUsageType() string {
	if x != nil {
		return x.UsageType
	}
	return ""
}

type DeleteAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentRequest) Reset() {
	*x = DeleteAttachmentRequest{}
	mi := &file_proto_content_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentRequest) ProtoMessage() {}

func (x *DeleteAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteAttachmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Comment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentId       int64                  `protobuf:"varint,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ParentCommentId int64                  `protobuf:"varint,3,opt,name=parent_comment_id,json=parentCommentId,proto3" json:"parent_comment_id,omitempty"`
	AuthorName      string                 `protobuf:"bytes,4,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail     string                 `protobuf:"bytes,5,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	BodyMarkdown    string                 `protobuf:"bytes,6,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ModerationNote  string                 `protobuf:"bytes,8,opt,name=moderation_note,json=moderationNote,proto3" json:"moderation_note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_proto_content_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{27}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *Comment) GetParentCommentId() int64 {
	if x != nil {
		return x.ParentCommentId
	}
	return 0
}

func (x *Comment) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Comment) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *Comment) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

func (x *Comment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Comment) GetModerationNote() string {
	if x != nil {
		return x.ModerationNote
	}
	return ""
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_proto_content_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{28}
}

func (x *ListCommentsRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *ListCommentsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Comment             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_proto_content_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{29}
}

func (x *ListCommentsResponse) GetList() []*Comment {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateCommentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentId       int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ParentCommentId int64                  `protobuf:"varint,2,opt,name=parent_comment_id,json=parentCommentId,proto3" json:"parent_comment_id,omitempty"`
	AuthorName      string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail     string                 `protobuf:"bytes,4,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	BodyMarkdown    string                 `protobuf:"bytes,5,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_proto_content_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{30}
}

func (x *CreateCommentRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *CreateCommentRequest) GetParentCommentId() int64 {
	if x != nil {
		return x.ParentCommentId
	}
	return 0
}

func (x *CreateCommentRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *CreateCommentRequest) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *CreateCommentRequest) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

type UpdateCommentStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ModerationNote string                 `protobuf:"bytes,3,opt,name=moderation_note,json=moderationNote,proto3" json:"moderation_note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCommentStatusRequest) Reset() {
	*x = UpdateCommentStatusRequest{}
	mi := &file_proto_content_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentStatusRequest) ProtoMessage() {}

func (x *UpdateCommentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateCommentStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCommentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateCommentStatusRequest) GetModerationNote() string {
	if x != nil {
		return x.ModerationNote
	}
	return ""
}

var File_proto_content_proto protoreflect.FileDescriptor

const file_proto_content_proto_rawDesc = "" +
	"\n" +
	"\x13proto/content.proto\x12\acontent\"\xf0\x01\n" +
	"\x0eContentSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tai_access\x18\b \x01(\tR\baiAccess\x12!\n" +
	"\fpublished_at\x18\t \x01(\tR\vpublishedAt\"\x9b\x04\n" +
	"\rContentDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12#\n" +
	"\rbody_markdown\x18\x06 \x01(\tR\fbodyMarkdown\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tai_access\x18\t \x01(\tR\baiAccess\x12@\n" +
	"\x0fproject_profile\x18\n" +
	" \x01(\v2\x17.content.ProjectProfileR\x0eprojectProfile\x12I\n" +
	"\x12experience_profile\x18\v \x01(\v2\x1a.content.ExperienceProfileR\x11experienceProfile\x12S\n" +
	"\x16timeline_event_profile\x18\f \x01(\v2\x1d.content.TimelineEventProfileR\x14timelineEventProfile\x12F\n" +
	"\x11portfolio_profile\x18\r \x01(\v2\x19.content.PortfolioProfileR\x10portfolioProfile\"\x8c\x01\n" +
	"\x13ListContentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"C\n" +
	"\x14ListContentsResponse\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.content.ContentSummaryR\x04list\"\xfa\x03\n" +
	"\x14CreateContentRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12#\n" +
	"\rbody_markdown\x18\x05 \x01(\tR\fbodyMarkdown\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tai_access\x18\a \x01(\tR\baiAccess\x12@\n" +
	"\x0fproject_profile\x18\b \x01(\v2\x17.content.ProjectProfileR\x0eprojectProfile\x12I\n" +
	"\x12experience_profile\x18\t \x01(\v2\x1a.content.ExperienceProfileR\x11experienceProfile\x12S\n" +
	"\x16timeline_event_profile\x18\n" +
	" \x01(\v2\x1d.content.TimelineEventProfileR\x14timelineEventProfile\x12F\n" +
	"\x11portfolio_profile\x18\v \x01(\v2\x19.content.PortfolioProfileR\x10portfolioProfile\"\xe2\x03\n" +
	"\x14UpdateContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12#\n" +
	"\rbody_markdown\x18\x04 \x01(\tR\fbodyMarkdown\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tai_access\x18\x06 \x01(\tR\baiAccess\x12@\n" +
	"\x0fproject_profile\x18\a \x01(\v2\x17.content.ProjectProfileR\x0eprojectProfile\x12I\n" +
	"\x12experience_profile\x18\b \x01(\v2\x1a.content.ExperienceProfileR\x11experienceProfile\x12S\n" +
	"\x16timeline_event_profile\x18\t \x01(\v2\x1d.content.TimelineEventProfileR\x14timelineEventProfile\x12F\n" +
	"\x11portfolio_profile\x18\n" +
	" \x01(\v2\x19.content.PortfolioProfileR\x10portfolioProfile\"=\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"#\n" +
	"\x11GetContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\a\n" +
	"\x05Empty\"\xb9\x01\n" +
	"\x0eProjectProfile\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12\x14\n" +
	"\x05stack\x18\x02 \x01(\tR\x05stack\x12\x19\n" +
	"\brepo_url\x18\x03 \x01(\tR\arepoUrl\x12\x19\n" +
	"\bdemo_url\x18\x04 \x01(\tR\ademoUrl\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x06 \x01(\tR\aendedAt\"\xa1\x01\n" +
	"\x11ExperienceProfile\x12\x19\n" +
	"\borg_name\x18\x01 \x01(\tR\aorgName\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\tR\aendedAt\"\\\n" +
	"\x14TimelineEventProfile\x12\x1d\n" +
	"\n" +
	"event_time\x18\x01 \x01(\tR\teventTime\x12%\n" +
	"\x0eevent_category\x18\x02 \x01(\tR\reventCategory\"\\\n" +
	"\x10PortfolioProfile\x12#\n" +
	"\rartifact_type\x18\x01 \x01(\tR\fartifactType\x12#\n" +
	"\rexternal_link\x18\x02 \x01(\tR\fexternalLink\"u\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"4\n" +
	"\x10ListTagsResponse\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.content.TagR\x04list\"r\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\"\n" +
	"\x10DeleteTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc3\x01\n" +
	"\bRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x11source_content_id\x18\x02 \x01(\x03R\x0fsourceContentId\x12*\n" +
	"\x11target_content_id\x18\x03 \x01(\x03R\x0ftargetContentId\x12#\n" +
	"\rrelation_type\x18\x04 \x01(\tR\frelationType\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"5\n" +
	"\x14ListRelationsRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\">\n" +
	"\x15ListRelationsResponse\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.content.RelationR\x04list\"\xc0\x01\n" +
	"\x15CreateRelationRequest\x12*\n" +
	"\x11source_content_id\x18\x01 \x01(\x03R\x0fsourceContentId\x12*\n" +
	"\x11target_content_id\x18\x02 \x01(\x03R\x0ftargetContentId\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"'\n" +
	"\x15DeleteRelationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa7\x02\n" +
	"\n" +
	"Attachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\x03R\tcontentId\x12)\n" +
	"\x10storage_provider\x18\x03 \x01(\tR\x0fstorageProvider\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x05 \x01(\tR\tobjectKey\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\x12\x10\n" +
	"\x03ext\x18\b \x01(\tR\x03ext\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\t \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"usage_type\x18\n" +
	" \x01(\tR\tusageType\"h\n" +
	"\x16ListAttachmentsRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"B\n" +
	"\x17ListAttachmentsResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.content.AttachmentR\x04list\"\xa4\x02\n" +
	"\x17CreateAttachmentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12)\n" +
	"\x10storage_provider\x18\x02 \x01(\tR\x0fstorageProvider\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x10\n" +
	"\x03ext\x18\a \x01(\tR\x03ext\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\b \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"usage_type\x18\t \x01(\tR\tusageType\")\n" +
	"\x17DeleteAttachmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\x03R\tcontentId\x12*\n" +
	"\x11parent_comment_id\x18\x03 \x01(\x03R\x0fparentCommentId\x12\x1f\n" +
	"\vauthor_name\x18\x04 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x05 \x01(\tR\vauthorEmail\x12#\n" +
	"\rbody_markdown\x18\x06 \x01(\tR\fbodyMarkdown\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12'\n" +
	"\x0fmoderation_note\x18\b \x01(\tR\x0emoderationNote\"e\n" +
	"\x13ListCommentsRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"<\n" +
	"\x14ListCommentsResponse\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.content.CommentR\x04list\"\xca\x01\n" +
	"\x14CreateCommentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12*\n" +
	"\x11parent_comment_id\x18\x02 \x01(\x03R\x0fparentCommentId\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x04 \x01(\tR\vauthorEmail\x12#\n" +
	"\rbody_markdown\x18\x05 \x01(\tR\fbodyMarkdown\"m\n" +
	"\x1aUpdateCommentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fmoderation_note\x18\x03 \x01(\tR\x0emoderationNote2\x88\n" +
	"\n" +
	"\aContent\x12Q\n" +
	"\x12ListPublicArticles\x12\x1c.content.ListContentsRequest\x1a\x1d.content.ListContentsResponse\x12K\n" +
	"\fListContents\x12\x1c.content.ListContentsRequest\x1a\x1d.content.ListContentsResponse\x12F\n" +
	"\rCreateContent\x12\x1d.content.CreateContentRequest\x1a\x16.content.ContentDetail\x12@\n" +
	"\n" +
	"GetContent\x12\x1a.content.GetContentRequest\x1a\x16.content.ContentDetail\x12F\n" +
	"\rUpdateContent\x12\x1d.content.UpdateContentRequest\x1a\x16.content.ContentDetail\x12K\n" +
	"\x13UpdateContentStatus\x12\x1c.content.UpdateStatusRequest\x1a\x16.content.ContentDetail\x125\n" +
	"\bListTags\x12\x0e.content.Empty\x1a\x19.content.ListTagsResponse\x124\n" +
	"\tCreateTag\x12\x19.content.CreateTagRequest\x1a\f.content.Tag\x126\n" +
	"\tDeleteTag\x12\x19.content.DeleteTagRequest\x1a\x0e.content.Empty\x12N\n" +
	"\rListRelations\x12\x1d.content.ListRelationsRequest\x1a\x1e.content.ListRelationsResponse\x12C\n" +
	"\x0eCreateRelation\x12\x1e.content.CreateRelationRequest\x1a\x11.content.Relation\x12@\n" +
	"\x0eDeleteRelation\x12\x1e.content.DeleteRelationRequest\x1a\x0e.content.Empty\x12T\n" +
	"\x0fListAttachments\x12\x1f.content.ListAttachmentsRequest\x1a .content.ListAttachmentsResponse\x12I\n" +
	"\x10CreateAttachment\x12 .content.CreateAttachmentRequest\x1a\x13.content.Attachment\x12D\n" +
	"\x10DeleteAttachment\x12 .content.DeleteAttachmentRequest\x1a\x0e.content.Empty\x12K\n" +
	"\fListComments\x12\x1c.content.ListCommentsRequest\x1a\x1d.content.ListCommentsResponse\x12@\n" +
	"\rCreateComment\x12\x1d.content.CreateCommentRequest\x1a\x10.content.Comment\x12L\n" +
	"\x13UpdateCommentStatus\x12#.content.UpdateCommentStatusRequest\x1a\x10.content.CommentB\x15Z\x13services/content/pbb\x06proto3"

var (
	file_proto_content_proto_rawDescOnce sync.Once
	file_proto_content_proto_rawDescData []byte
)

func file_proto_content_proto_rawDescGZIP() []byte {
	file_proto_content_proto_rawDescOnce.Do(func() {
		file_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)))
	})
	return file_proto_content_proto_rawDescData
}

var file_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_content_proto_goTypes = []any{
	(*ContentSummary)(nil),             // 0: content.ContentSummary
	(*ContentDetail)(nil),              // 1: content.ContentDetail
	(*ListContentsRequest)(nil),        // 2: content.ListContentsRequest
	(*ListContentsResponse)(nil),       // 3: content.ListContentsResponse
	(*CreateContentRequest)(nil),       // 4: content.CreateContentRequest
	(*UpdateContentRequest)(nil),       // 5: content.UpdateContentRequest
	(*UpdateStatusRequest)(nil),        // 6: content.UpdateStatusRequest
	(*GetContentRequest)(nil),          // 7: content.GetContentRequest
	(*Empty)(nil),                      // 8: content.Empty
	(*ProjectProfile)(nil),             // 9: content.ProjectProfile
	(*ExperienceProfile)(nil),          // 10: content.ExperienceProfile
	(*TimelineEventProfile)(nil),       // 11: content.TimelineEventProfile
	(*PortfolioProfile)(nil),           // 12: content.PortfolioProfile
	(*Tag)(nil),                        // 13: content.Tag
	(*ListTagsResponse)(nil),           // 14: content.ListTagsResponse
	(*CreateTagRequest)(nil),           // 15: content.CreateTagRequest
	(*DeleteTagRequest)(nil),           // 16: content.DeleteTagRequest
	(*Relation)(nil),                   // 17: content.Relation
	(*ListRelationsRequest)(nil),       // 18: content.ListRelationsRequest
	(*ListRelationsResponse)(nil),      // 19: content.ListRelationsResponse
	(*CreateRelationRequest)(nil),      // 20: content.CreateRelationRequest
	(*DeleteRelationRequest)(nil),      // 21: content.DeleteRelationRequest
	(*Attachment)(nil),                 // 22: content.Attachment
	(*ListAttachmentsRequest)(nil),     // 23: content.ListAttachmentsRequest
	(*ListAttachmentsResponse)(nil),    // 24: content.ListAttachmentsResponse
	(*CreateAttachmentRequest)(nil),    // 25: content.CreateAttachmentRequest
	(*DeleteAttachmentRequest)(nil),    // 26: content.DeleteAttachmentRequest
	(*Comment)(nil),                    // 27: content.Comment
	(*ListCommentsRequest)(nil),        // 28: content.ListCommentsRequest
	(*ListCommentsResponse)(nil),       // 29: content.ListCommentsResponse
	(*CreateCommentRequest)(nil),       // 30: content.CreateCommentRequest
	(*UpdateCommentStatusRequest)(nil), // 31: content.UpdateCommentStatusRequest
}
var file_proto_content_proto_depIdxs = []int32{
	9,  // 0: content.ContentDetail.project_profile:type_name -> content.ProjectProfile
	10, // 1: content.ContentDetail.experience_profile:type_name -> content.ExperienceProfile
	11, // 2: content.ContentDetail.timeline_event_profile:type_name -> content.TimelineEventProfile
	12, // 3: content.ContentDetail.portfolio_profile:type_name -> content.PortfolioProfile
	0,  // 4: content.ListContentsResponse.list:type_name -> content.ContentSummary
	9,  // 5: content.CreateContentRequest.project_profile:type_name -> content.ProjectProfile
	10, // 6: content.CreateContentRequest.experience_profile:type_name -> content.ExperienceProfile
	11, // 7: content.CreateContentRequest.timeline_event_profile:type_name -> content.TimelineEventProfile
	12, // 8: content.CreateContentRequest.portfolio_profile:type_name -> content.PortfolioProfile
	9,  // 9: content.UpdateContentRequest.project_profile:type_name -> content.ProjectProfile
	10, // 10: content.UpdateContentRequest.experience_profile:type_name -> content.ExperienceProfile
	11, // 11: content.UpdateContentRequest.timeline_event_profile:type_name -> content.TimelineEventProfile
	12, // 12: content.UpdateContentRequest.portfolio_profile:type_name -> content.PortfolioProfile
	13, // 13: content.ListTagsResponse.list:type_name -> content.Tag
	17, // 14: content.ListRelationsResponse.list:type_name -> content.Relation
	22, // 15: content.ListAttachmentsResponse.list:type_name -> content.Attachment
	27, // 16: content.ListCommentsResponse.list:type_name -> content.Comment
	2,  // 17: content.Content.ListPublicArticles:input_type -> content.ListContentsRequest
	2,  // 18: content.Content.ListContents:input_type -> content.ListContentsRequest
	4,  // 19: content.Content.CreateContent:input_type -> content.CreateContentRequest
	7,  // 20: content.Content.GetContent:input_type -> content.GetContentRequest
	5,  // 21: content.Content.UpdateContent:input_type -> content.UpdateContentRequest
	6,  // 22: content.Content.UpdateContentStatus:input_type -> content.UpdateStatusRequest
	8,  // 23: content.Content.ListTags:input_type -> content.Empty
	15, // 24: content.Content.CreateTag:input_type -> content.CreateTagRequest
	16, // 25: content.Content.DeleteTag:input_type -> content.DeleteTagRequest
	18, // 26: content.Content.ListRelations:input_type -> content.ListRelationsRequest
	20, // 27: content.Content.CreateRelation:input_type -> content.CreateRelationRequest
	21, // 28: content.Content.DeleteRelation:input_type -> content.DeleteRelationRequest
	23, // 29: content.Content.ListAttachments:input_type -> content.ListAttachmentsRequest
	25, // 30: content.Content.CreateAttachment:input_type -> content.CreateAttachmentRequest
	26, // 31: content.Content.DeleteAttachment:input_type -> content.DeleteAttachmentRequest
	28, // 32: content.Content.ListComments:input_type -> content.ListCommentsRequest
	30, // 33: content.Content.CreateComment:input_type -> content.CreateCommentRequest
	31, // 34: content.Content.UpdateCommentStatus:input_type -> content.UpdateCommentStatusRequest
	3,  // 35: content.Content.ListPublicArticles:output_type -> content.ListContentsResponse
	3,  // 36: content.Content.ListContents:output_type -> content.ListContentsResponse
	1,  // 37: content.Content.CreateContent:output_type -> content.ContentDetail
	1,  // 38: content.Content.GetContent:output_type -> content.ContentDetail
	1,  // 39: content.Content.UpdateContent:output_type -> content.ContentDetail
	1,  // 40: content.Content.UpdateContentStatus:output_type -> content.ContentDetail
	14, // 41: content.Content.ListTags:output_type -> content.ListTagsResponse
	13, // 42: content.Content.CreateTag:output_type -> content.Tag
	8,  // 43: content.Content.DeleteTag:output_type -> content.Empty
	19, // 44: content.Content.ListRelations:output_type -> content.ListRelationsResponse
	17, // 45: content.Content.CreateRelation:output_type -> content.Relation
	8,  // 46: content.Content.DeleteRelation:output_type -> content.Empty
	24, // 47: content.Content.ListAttachments:output_type -> content.ListAttachmentsResponse
	22, // 48: content.Content.CreateAttachment:output_type -> content.Attachment
	8,  // 49: content.Content.DeleteAttachment:output_type -> content.Empty
	29, // 50: content.Content.ListComments:output_type -> content.ListCommentsResponse
	27, // 51: content.Content.CreateComment:output_type -> content.Comment
	27, // 52: content.Content.UpdateCommentStatus:output_type -> content.Comment
	35, // [35:53] is the sub-list for method output_type
	17, // [17:35] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_content_proto_init() }
func file_proto_content_proto_init() {
	if File_proto_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_content_proto_goTypes,
		DependencyIndexes: file_proto_content_proto_depIdxs,
		MessageInfos:      file_proto_content_proto_msgTypes,
	}.Build()
	File_proto_content_proto = out.File
	file_proto_content_proto_goTypes = nil
	file_proto_content_proto_depIdxs = nil
}
