// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/content/internal/logic"
	"github.com/HappyLadySauce/Beehive-Blog/services/content/internal/svc"
	"github.com/HappyLadySauce/Beehive-Blog/services/content/pb"
)

type ContentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedContentServer
}

func NewContentServer(svcCtx *svc.ServiceContext) *ContentServer {
	return &ContentServer{
		svcCtx: svcCtx,
	}
}

func (s *ContentServer) ListPublicArticles(ctx context.Context, in *pb.ListContentsRequest) (*pb.ListContentsResponse, error) {
	l := logic.NewListPublicArticlesLogic(ctx, s.svcCtx)
	return l.ListPublicArticles(in)
}

func (s *ContentServer) ListContents(ctx context.Context, in *pb.ListContentsRequest) (*pb.ListContentsResponse, error) {
	l := logic.NewListContentsLogic(ctx, s.svcCtx)
	return l.ListContents(in)
}

func (s *ContentServer) CreateContent(ctx context.Context, in *pb.CreateContentRequest) (*pb.ContentDetail, error) {
	l := logic.NewCreateContentLogic(ctx, s.svcCtx)
	return l.CreateContent(in)
}

func (s *ContentServer) GetContent(ctx context.Context, in *pb.GetContentRequest) (*pb.ContentDetail, error) {
	l := logic.NewGetContentLogic(ctx, s.svcCtx)
	return l.GetContent(in)
}

func (s *ContentServer) UpdateContent(ctx context.Context, in *pb.UpdateContentRequest) (*pb.ContentDetail, error) {
	l := logic.NewUpdateContentLogic(ctx, s.svcCtx)
	return l.UpdateContent(in)
}

func (s *ContentServer) UpdateContentStatus(ctx context.Context, in *pb.UpdateStatusRequest) (*pb.ContentDetail, error) {
	l := logic.NewUpdateContentStatusLogic(ctx, s.svcCtx)
	return l.UpdateContentStatus(in)
}
