// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/search/internal/logic"
	"github.com/HappyLadySauce/Beehive-Blog/services/search/internal/svc"
	"github.com/HappyLadySauce/Beehive-Blog/services/search/pb"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServer) Query(ctx context.Context, in *pb.SearchRequest) (*pb.SearchResponse, error) {
	l := logic.NewQueryLogic(ctx, s.svcCtx)
	return l.Query(in)
}

func (s *SearchServer) UpsertDocument(ctx context.Context, in *pb.UpsertDocumentRequest) (*pb.IndexDocument, error) {
	l := logic.NewUpsertDocumentLogic(ctx, s.svcCtx)
	return l.UpsertDocument(in)
}

func (s *SearchServer) DeleteDocument(ctx context.Context, in *pb.DeleteDocumentRequest) (*pb.Empty, error) {
	l := logic.NewDeleteDocumentLogic(ctx, s.svcCtx)
	return l.DeleteDocument(in)
}
