// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	gateway "github.com/HappyLadySauce/Beehive-Blog/services/gateway/internal/handler/gateway"
	"github.com/HappyLadySauce/Beehive-Blog/services/gateway/internal/middleware"
	"github.com/HappyLadySauce/Beehive-Blog/services/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	authMiddleware := middleware.NewAuthMiddleware(serverCtx)
	rateLimitMiddleware := middleware.NewRateLimitMiddleware(serverCtx.Config.RateLimit)
	requestIDMiddleware := middleware.NewRequestIDMiddleware()

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{requestIDMiddleware.Handle, rateLimitMiddleware.Handle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/login",
					Handler: gateway.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/refresh",
					Handler: gateway.RefreshHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/register",
					Handler: gateway.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: gateway.HealthzHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/public/articles",
					Handler: gateway.ListArticlesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search/query",
					Handler: gateway.QueryHandler(serverCtx),
				},
			}...),
		rest.WithPrefix("/api/v2"),
	)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{requestIDMiddleware.Handle, rateLimitMiddleware.Handle, authMiddleware.Handle},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/auth/me",
					Handler: gateway.MeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/studio/contents",
					Handler: gateway.ListContentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/studio/contents",
					Handler: gateway.CreateContentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/studio/contents/:id",
					Handler: gateway.GetContentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/studio/contents/:id",
					Handler: gateway.UpdateContentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/studio/contents/:id/status",
					Handler: gateway.UpdateContentStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/studio/tags",
					Handler: gateway.ListTagsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/studio/tags",
					Handler: gateway.CreateTagHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/studio/tags/:id",
					Handler: gateway.DeleteTagHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/studio/contents/:id/relations",
					Handler: gateway.ListRelationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/studio/contents/:id/relations",
					Handler: gateway.CreateRelationHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/studio/relations/:id",
					Handler: gateway.DeleteRelationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/studio/attachments",
					Handler: gateway.ListAttachmentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/studio/attachments",
					Handler: gateway.CreateAttachmentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/studio/attachments/:id",
					Handler: gateway.DeleteAttachmentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/studio/contents/:id/comments",
					Handler: gateway.ListCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/studio/contents/:id/comments",
					Handler: gateway.CreateCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/studio/comments/:id/status",
					Handler: gateway.UpdateCommentStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/studio/search/query",
					Handler: gateway.QueryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/studio/search/index/contents/:id",
					Handler: gateway.ReindexContentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/studio/search/index/contents/:id",
					Handler: gateway.DeleteSearchIndexHandler(serverCtx),
				},
			}...),
		rest.WithPrefix("/api/v2"),
	)
}
