// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: indexer.proto

package indexer

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/indexer/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty              = pb.Empty
	HealthResponse     = pb.HealthResponse
	SyncOutboxRequest  = pb.SyncOutboxRequest
	SyncOutboxResponse = pb.SyncOutboxResponse

	Indexer interface {
		SyncOutbox(ctx context.Context, in *SyncOutboxRequest, opts ...grpc.CallOption) (*SyncOutboxResponse, error)
		Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	}

	defaultIndexer struct {
		cli zrpc.Client
	}
)

func NewIndexer(cli zrpc.Client) Indexer {
	return &defaultIndexer{
		cli: cli,
	}
}

func (m *defaultIndexer) SyncOutbox(ctx context.Context, in *SyncOutboxRequest, opts ...grpc.CallOption) (*SyncOutboxResponse, error) {
	client := pb.NewIndexerClient(m.cli.Conn())
	return client.SyncOutbox(ctx, in, opts...)
}

func (m *defaultIndexer) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	client := pb.NewIndexerClient(m.cli.Conn())
	return client.Health(ctx, in, opts...)
}
