// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package identity

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/identity/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserRequest  = pb.GetUserRequest
	LoginRequest    = pb.LoginRequest
	RefreshRequest  = pb.RefreshRequest
	RegisterRequest = pb.RegisterRequest
	TokenReply      = pb.TokenReply
	UserProfile     = pb.UserProfile

	Identity interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*TokenReply, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenReply, error)
		Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenReply, error)
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserProfile, error)
	}

	defaultIdentity struct {
		cli zrpc.Client
	}
)

func NewIdentity(cli zrpc.Client) Identity {
	return &defaultIdentity{
		cli: cli,
	}
}

func (m *defaultIdentity) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultIdentity) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultIdentity) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.Refresh(ctx, in, opts...)
}

func (m *defaultIdentity) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
