// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package search

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/search/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SearchRequest    = pb.SearchRequest
	SearchResponse   = pb.SearchResponse
	SearchResultItem = pb.SearchResultItem

	Search interface {
		Query(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	}

	defaultSearch struct {
		cli zrpc.Client
	}
)

func NewSearch(cli zrpc.Client) Search {
	return &defaultSearch{
		cli: cli,
	}
}

func (m *defaultSearch) Query(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	client := pb.NewSearchClient(m.cli.Conn())
	return client.Query(ctx, in, opts...)
}
