// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package search

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/search/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SearchRequest         = pb.SearchRequest
	SearchResponse        = pb.SearchResponse
	SearchResultItem      = pb.SearchResultItem
	UpsertDocumentRequest = pb.UpsertDocumentRequest
	IndexDocument         = pb.IndexDocument
	DeleteDocumentRequest = pb.DeleteDocumentRequest
	Empty                 = pb.Empty

	Search interface {
		Query(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
		UpsertDocument(ctx context.Context, in *UpsertDocumentRequest, opts ...grpc.CallOption) (*IndexDocument, error)
		DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultSearch struct {
		cli zrpc.Client
	}
)

func NewSearch(cli zrpc.Client) Search {
	return &defaultSearch{
		cli: cli,
	}
}

func (m *defaultSearch) Query(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	client := pb.NewSearchClient(m.cli.Conn())
	return client.Query(ctx, in, opts...)
}

func (m *defaultSearch) UpsertDocument(ctx context.Context, in *UpsertDocumentRequest, opts ...grpc.CallOption) (*IndexDocument, error) {
	client := pb.NewSearchClient(m.cli.Conn())
	return client.UpsertDocument(ctx, in, opts...)
}

func (m *defaultSearch) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSearchClient(m.cli.Conn())
	return client.DeleteDocument(ctx, in, opts...)
}
