// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/github/authorize": {
            "get": {
                "description": "Returns a one-time state string and full auth_url for the browser redirect. After GitHub redirects back with code, call POST /api/v1/auth/login with grant_type github_oauth2, code, and the same state.\n返回一次性 state 与完整 auth_url 供浏览器跳转。GitHub 回调携带 code 后，使用 grant_type=github_oauth2、code 与本 state 调用 POST /api/v1/auth/login。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start GitHub OAuth2 (state + authorize URL)",
                "responses": {
                    "200": {
                        "description": "state and auth_url",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.GithubOAuthBeginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Redis or configuration error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates by grant_type. Use grant_type=local with account (username or email) and password, or grant_type=github_oauth2 with code and state from GET /api/v1/auth/github/authorize. 中文：按 grant_type 登录；local 使用用户名或邮箱与密码；github_oauth2 使用授权码与 state。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login (local password or GitHub OAuth2)",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Issued access and refresh tokens",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation error or unsupported grant_type",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or invalid OAuth code/state",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Account status disallows login",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes the server-side session tied to the presented access token. Reuse detection on refresh tokens is unaffected. 中文：撤销当前 access token 对应的服务端会话；与 refresh 轮换检测无关。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout (revoke current session)",
                "responses": {
                    "200": {
                        "description": "data is an empty JSON object",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Rotates the refresh session and returns a new access + refresh pair. Reuse of an old refresh token may revoke the session family. 中文：轮换 refresh 会话并返回新的令牌对；重复使用旧 refresh 可能导致会话族被吊销。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New token pair",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.RefreshResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Invalid, expired, or reused refresh token",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "User status disallows login",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/session": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verifies the presented access token and returns the signed session claims used by browser-side BFF guards. 中文：校验传入的 access token，并返回浏览器 BFF 守卫使用的已签名会话声明。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current auth session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.AuthSessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/settings/attachment": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns sanitized attachment storage and validation settings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get attachment settings (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SettingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Merges attachment subtree; omit fields to keep existing.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Patch attachment settings (admin)",
                "parameters": [
                    {
                        "description": "Partial attachment settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AttachmentPatchJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SettingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/settings/email": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns sanitized settings including email SMTP flags without secrets. 中文：返回脱敏应用设置（含 SMTP 开关，不含密码明文）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get application settings (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SettingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Merges email subtree; omit password to keep existing. Empty string clears password. 中文：合并 email 子树；省略 password 表示不改；传空字符串清空密码。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Patch application settings (admin)",
                "parameters": [
                    {
                        "description": "Partial settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SettingsPatchRequestJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SettingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/settings/email/test": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a test email to the requested recipient using saved SMTP settings. 中文：使用已保存 SMTP 设置向指定收件人发送测试邮件。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Send SMTP test email (admin)",
                "parameters": [
                    {
                        "description": "Test recipient",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SettingsEmailTestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SettingsEmailTestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/settings/github-oauth2": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns sanitized GitHub OAuth2 settings without client secret.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get GitHub OAuth2 settings (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SettingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Merges github_oauth2 subtree; omit fields to keep existing. Pass empty string to clear.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Patch GitHub OAuth2 settings (admin)",
                "parameters": [
                    {
                        "description": "Partial GitHub OAuth2 settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GithubOAuth2PatchJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SettingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Paginated list with optional status, role and search filters. 中文：分页用户列表，支持状态、角色和搜索筛选。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "active",
                            "disabled",
                            "locked",
                            "pending"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "member",
                            "admin"
                        ],
                        "type": "string",
                        "description": "Filter by role",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search username or email",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.ListUsersResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin creates a user with optional password. 中文：管理员创建用户，可附带密码。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "Create user payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.CreateUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/register": {
            "post": {
                "description": "Creates identity.users plus credentials and returns tokens (auto-login). Avatar binding is deferred until authenticated flows. 中文：创建用户与凭证并返回令牌（自动登录）；头像请在登录态流程中再绑定。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Issued access and refresh tokens",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "409": {
                        "description": "Username or email conflict",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns full user detail by ID. 中文：根据 ID 返回用户完整详情。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.UserDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft-deletes a user by ID. 中文：根据 ID 软删除用户。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partially update user fields. Pointer fields: nil=unchanged, \"\"=clear, \"v\"=set. 中文：部分更新用户字段。指针字段：nil=不修改，空串=清空，有值=设置。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update user payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.UpdateUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.AttachmentPatchJSON": {
            "type": "object",
            "properties": {
                "allowed_mime_prefixes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "default_storage": {
                    "type": "string"
                },
                "local_root": {
                    "type": "string"
                },
                "max_bytes": {
                    "type": "integer"
                },
                "oss": {
                    "$ref": "#/definitions/v1.AttachmentRemotePatchJSON"
                },
                "presign_ttl_seconds": {
                    "type": "integer"
                },
                "s3": {
                    "$ref": "#/definitions/v1.AttachmentRemotePatchJSON"
                }
            }
        },
        "v1.AttachmentRemotePatchJSON": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "download_base_url": {
                    "type": "string"
                },
                "upload_base_url": {
                    "type": "string"
                }
            }
        },
        "v1.AttachmentRemoteSettingsPublic": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "download_base_url": {
                    "type": "string"
                },
                "upload_base_url": {
                    "type": "string"
                }
            }
        },
        "v1.AttachmentSettingsPublic": {
            "type": "object",
            "properties": {
                "allowed_mime_prefixes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "default_storage": {
                    "type": "string"
                },
                "local_root": {
                    "type": "string"
                },
                "max_bytes": {
                    "type": "integer"
                },
                "oss": {
                    "$ref": "#/definitions/v1.AttachmentRemoteSettingsPublic"
                },
                "presign_ttl_seconds": {
                    "type": "integer"
                },
                "s3": {
                    "$ref": "#/definitions/v1.AttachmentRemoteSettingsPublic"
                }
            }
        },
        "v1.AuthSessionResponse": {
            "type": "object",
            "properties": {
                "exp": {
                    "description": "Exp is the access token expiration time as a Unix timestamp.\nExp 为 access token 的过期时间（Unix 时间戳）。",
                    "type": "integer"
                },
                "role": {
                    "description": "Role is the authenticated user's authorization role.\nRole 为已认证用户的授权角色。",
                    "type": "string"
                },
                "sid": {
                    "description": "SID is the server-side session ID bound to the access token.\nSID 为 access token 绑定的服务端会话 ID。",
                    "type": "integer"
                },
                "uid": {
                    "description": "UID is the authenticated user ID from the verified access token.\nUID 为已验证 access token 中的用户 ID。",
                    "type": "integer"
                }
            }
        },
        "v1.AuthToken": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "AccessToken is the short-lived bearer token used in the Authorization header.\nAccessToken 为短期 Bearer 令牌，用于 Authorization 请求头。",
                    "type": "string"
                },
                "expires_in": {
                    "description": "ExpiresIn is the access token lifetime in seconds.\nExpiresIn 为访问令牌的有效期（秒）。",
                    "type": "integer"
                },
                "refresh_token": {
                    "description": "RefreshToken is an optional long-lived credential to mint new access tokens; omit when not issued.\nRefreshToken 为可选的长期凭证，用于刷新访问令牌；未签发时不输出该字段。",
                    "type": "string"
                },
                "token_type": {
                    "description": "TokenType is the credential scheme; \"Bearer\" for OAuth2-compatible clients.\nTokenType 为凭证类型；OAuth2 客户端固定为 \"Bearer\"。",
                    "type": "string"
                }
            }
        },
        "v1.CreateUserRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 320
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 128
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                },
                "phone": {
                    "type": "string",
                    "maxLength": 16
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "member",
                        "admin"
                    ]
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "disabled",
                        "locked",
                        "pending"
                    ]
                },
                "username": {
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "v1.CreateUserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "v1.EmailSMTPPatchJSON": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "from": {
                    "type": "string"
                },
                "from_name": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "tls": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.EmailSettingsPublic": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "from": {
                    "type": "string"
                },
                "from_name": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password_set": {
                    "type": "boolean"
                },
                "port": {
                    "type": "integer"
                },
                "tls": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.GithubOAuth2PatchJSON": {
            "type": "object",
            "properties": {
                "allow_non_github_endpoints": {
                    "type": "boolean"
                },
                "auth_url": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "redirect_url": {
                    "type": "string"
                },
                "token_url": {
                    "type": "string"
                },
                "user_info_url": {
                    "type": "string"
                }
            }
        },
        "v1.GithubOAuth2SettingsPublic": {
            "type": "object",
            "properties": {
                "allow_non_github_endpoints": {
                    "type": "boolean"
                },
                "auth_url": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "client_secret_set": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "redirect_url": {
                    "type": "string"
                },
                "token_url": {
                    "type": "string"
                },
                "user_info_url": {
                    "type": "string"
                }
            }
        },
        "v1.GithubOAuthBeginResponse": {
            "type": "object",
            "properties": {
                "auth_url": {
                    "description": "AuthURL is the full GitHub authorize URL including client_id, redirect_uri, scope, and state.\nAuthURL 为完整的 GitHub 授权 URL（含 client_id、redirect_uri、scope、state）。",
                    "type": "string"
                },
                "state": {
                    "description": "State must be echoed to POST /auth/login (github_oauth2) and matches a Redis one-time entry.\nState 必须在 POST /auth/login（github_oauth2）回传，并与 Redis 中一次性条目匹配。",
                    "type": "string"
                }
            }
        },
        "v1.ListUsersResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.UserItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1.LoginRequest": {
            "type": "object",
            "required": [
                "grant_type"
            ],
            "properties": {
                "account": {
                    "description": "Account is the local login account; required when grant_type is \"local\".\nAccount 为本地登录名；grant_type 为 \"local\" 时必填。",
                    "type": "string",
                    "maxLength": 64
                },
                "code": {
                    "description": "Code is the OAuth2 authorization code; required when grant_type is \"github_oauth2\".\nCode 为 OAuth2 授权码；grant_type 为 \"github_oauth2\" 时必填。",
                    "type": "string"
                },
                "grant_type": {
                    "description": "GrantType selects the authentication method: \"local\" or \"github_oauth2\".\nGrantType 选择认证方式：\"local\" 或 \"github_oauth2\"。",
                    "type": "string"
                },
                "password": {
                    "description": "Password is the local plaintext credential; required when grant_type is \"local\".\nPassword 为本地明文密码；grant_type 为 \"local\" 时必填。",
                    "type": "string",
                    "maxLength": 72
                },
                "state": {
                    "description": "State is the OAuth2 state parameter for CSRF protection.\nState 是 OAuth2 的 state 参数，用于 CSRF 防护。",
                    "type": "string"
                }
            }
        },
        "v1.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token is the auth credential bundle granted on successful login (auto-login).\nToken 为登录成功后自动签发的鉴权凭证集合（自动登录）。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.AuthToken"
                        }
                    ]
                }
            }
        },
        "v1.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "v1.RefreshResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "$ref": "#/definitions/v1.AuthToken"
                }
            }
        },
        "v1.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "Email is optional; when set must be unique among live rows (max 320 per DB).\nEmail 可选；有值时在活跃行内唯一（数据库最长 320）。",
                    "type": "string",
                    "maxLength": 320
                },
                "nickname": {
                    "description": "Nickname is an optional display name (max 128 per DB).\nNickname 为可选展示昵称（数据库最长 128）。",
                    "type": "string",
                    "maxLength": 128
                },
                "password": {
                    "description": "Password is the plaintext credential for hashing upstream of persistence (not a DB column yet).\nPassword 为明文凭证，供持久化前哈希使用（当前迁移尚无对应列）。",
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                },
                "phone": {
                    "description": "Phone is an optional phone number (max 16 per DB).\nPhone 为可选手机号（数据库最长 16）。",
                    "type": "string",
                    "maxLength": 16
                },
                "username": {
                    "description": "Username is the unique login name among live rows (max 64 per DB).\nUsername 为活跃行内唯一的登录名（数据库最长 64）。",
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "v1.RegisterResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token is the auth credential bundle granted on successful registration (auto-login).\nToken 为注册成功后自动签发的鉴权凭证集合（自动登录）。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.AuthToken"
                        }
                    ]
                }
            }
        },
        "v1.SettingsEmailTestRequest": {
            "type": "object",
            "required": [
                "recipient"
            ],
            "properties": {
                "recipient": {
                    "type": "string",
                    "maxLength": 320
                }
            }
        },
        "v1.SettingsEmailTestResponse": {
            "type": "object",
            "properties": {
                "recipient": {
                    "type": "string"
                }
            }
        },
        "v1.SettingsPatchRequestJSON": {
            "type": "object",
            "properties": {
                "attachment": {
                    "$ref": "#/definitions/v1.AttachmentPatchJSON"
                },
                "email": {
                    "$ref": "#/definitions/v1.EmailSMTPPatchJSON"
                },
                "github_oauth2": {
                    "$ref": "#/definitions/v1.GithubOAuth2PatchJSON"
                }
            }
        },
        "v1.SettingsResponse": {
            "type": "object",
            "properties": {
                "attachment": {
                    "$ref": "#/definitions/v1.AttachmentSettingsPublic"
                },
                "email": {
                    "$ref": "#/definitions/v1.EmailSettingsPublic"
                },
                "github_oauth2": {
                    "$ref": "#/definitions/v1.GithubOAuth2SettingsPublic"
                },
                "revision": {
                    "type": "integer"
                }
            }
        },
        "v1.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 320
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 128
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                },
                "phone": {
                    "type": "string",
                    "maxLength": 16
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "member",
                        "admin"
                    ]
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "disabled",
                        "locked",
                        "pending"
                    ]
                },
                "username": {
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "v1.UpdateUserResponse": {
            "type": "object",
            "properties": {
                "avatar_attachment_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_login_at": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.UserDetailResponse": {
            "type": "object",
            "properties": {
                "avatar_attachment_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_login_at": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.UserItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_login_at": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Send header Authorization with value \"Bearer \" plus the JWT access token. 中文：请求头 Authorization，值为 Bearer、空格与 access token 拼接。",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Beehive Blog HTTP API",
	Description:      "REST API for Beehive Blog (v1). JSON envelope: code (HTTP-style), message, data. 中文：Beehive Blog REST API（v1）；响应为 code、message、data 的 JSON 包装。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
