// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: indexer.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog/services/indexer/internal/logic"
	"github.com/HappyLadySauce/Beehive-Blog/services/indexer/internal/svc"
	"github.com/HappyLadySauce/Beehive-Blog/services/indexer/pb"
)

type IndexerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIndexerServer
}

func NewIndexerServer(svcCtx *svc.ServiceContext) *IndexerServer {
	return &IndexerServer{
		svcCtx: svcCtx,
	}
}

func (s *IndexerServer) SyncOutbox(ctx context.Context, in *pb.SyncOutboxRequest) (*pb.SyncOutboxResponse, error) {
	l := logic.NewSyncOutboxLogic(ctx, s.svcCtx)
	return l.SyncOutbox(in)
}

func (s *IndexerServer) Health(ctx context.Context, in *pb.Empty) (*pb.HealthResponse, error) {
	l := logic.NewHealthLogic(ctx, s.svcCtx)
	return l.Health(in)
}
